#!/bin/bash

set -eo pipefail

#
# This script makes the preparations
# needed to run Behat tests.
#

# Wake the multidev environment before running tests
terminus -n env:wake $TERMINUS_SITE.$TERMINUS_ENV

# Ping Drush to start ssh with the app server
terminus -n drush $TERMINUS_SITE.$TERMINUS_ENV -- version

# Create a backup before running Behat tests
terminus -n backup:create $TERMINUS_SITE.$TERMINUS_ENV --element=database

# Clear the environment cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV
