#!/usr/bin/env bash

## Runs phpcbf to clean up code-sniffer errors.

# Abort if anything fails
set -e
source ${PROJECT_ROOT}/.docksal/vars/colors

SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"
WEB_CONTAINER_PROJECT_ROOT="/var/www"
PHPCS="${WEB_CONTAINER_PROJECT_ROOT}/vendor/bin/phpcs"
PHPCBF="${WEB_CONTAINER_PROJECT_ROOT}/vendor/bin/phpcbf"

# Yes/no confirmation dialog with an optional message
# @param $1 confirmation message
_confirm ()
{

while true; do
    read -p "$1 [y/n]: " answer
    case "$answer" in
        [Yy]|[Yy][Ee][Ss] )
            break
            ;;
        [Nn]|[Nn][Oo] )
            exit 1
            ;;
        * )
        echo 'Please answer yes or no.'
    esac
done
}

# Exits fin if previous command exited with non-zero code
if_failed ()
{
    if [ ! $? -eq 0 ]; then
        echo-red "$*"
        exit 1
    fi
}

cd $PROJECT_ROOT

# Make sure Composer dependencies are installed
if [[ ! -d "$PROJECT_ROOT/vendor/squizlabs" ]]; then
	fin exec "cd $PROJECT_ROOT && composer install --prefer-source --no-interaction"
fi

if [[ ! -x "$PROJECT_ROOT/vendor/bin/phpcs" ]]; then
    echo -e "${yellow} bin/phpcs AND bin/phpcbf ${NC} are not set to be executable."
    _confirm "Fix automatically?"
    chmod +x "$PROJECT_ROOT/vendor/bin/phpcs"
    chmod +x "$PROJECT_ROOT/vendor/bin/phpcbf"
    if_failed "Could not make $PROJECT_ROOT/vendor/bin/phpcs or $PROJECT_ROOT/vendor/bin/phpcbf executable"
fi

fin exec "$PHPCS --config-set installed_paths $WEB_CONTAINER_PROJECT_ROOT/vendor/drupal/coder/coder_sniffer"
fin exec "$PHPCS --config-set colors 1"
fin exec "composer code-fix"
